# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AZ-PAYG(2)(ef69ddac-98e8-4607-aad6-d2d109143798)'
    ScriptType: 'FilePath'
    ScriptPath: 'scripts/build.ps1'
    ScriptArguments: '-Verbose'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/blog'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/blog'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DataBlogArtifact'
    publishLocation: 'Container'