name: Tag master merge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Version Number
      id: ver
      run: |
        $xml = [xml](Get-Content -Path "${$env:GITHUB_WORKSPACE}/src/common/version.xml" -Raw)
        $version = "$($xml.version.major).$($xml.version.minor).${$env:GITHUB_RUN_NUMBER}"
        Write-Verbose "Returning version: $version"
        echo "::set-output name=version_number::$version"
      shell: pwsh

    - name: Create Tag
      run: |
        curl \
          --request post \
          --url https://api.github.com/repos/${{ github.repository }}/git/tags \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "tag": "${{ steps.ver.version_number }}",
            "message": "Release version ${{ steps.ver.version_number }}",
            "object": "${{ github.sha }}",
            "type": "commit"
          }'

    - name: Create Tag Reference
      run: |
        curl \
          --request post \
          --url /repos/${{ github.repository }}/git/refs \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "ref": "refs/head/master",
            "sha": "${{ github.sha }}"
          }'
