name: Tag master merge

on:
  push:
    branches: [ master ]

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Version Number
      id: ver
      run: |
        $xml = [xml](Get-Content -Path "${env:GITHUB_WORKSPACE}/src/common/version.xml" -Raw)
        $version = "$($xml.version.major).$($xml.version.minor).${env:GITHUB_RUN_NUMBER}"
        Write-Verbose "Returning version: $version"
        echo "::set-env name=version_number::$version"
      shell: pwsh

    - name: Tag Commit with Version Number
      uses: tvdias/github-tagger@v0.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: $version_number
        commit-sha: ${{ github.sha }}

