name: Tag master merge

on:
  push:
    branches: [ master ]

jobs:
  tag_release_job:
    runs-on: ubuntu-latest
    name: Tag Release Job

    steps:
    - uses: actions/checkout@v2

    - name: Get Version Number
      id: ver
      run: |
        $version = src/common/Get-VersionNumber.ps1
        echo "::set-env name=version_number::$version"
      shell: pwsh

    - name: Create a Release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version_number }}
        release_name: "Release ${{ env.version_number }}"
        prerelease: true
        commitish: ${{ github.sha }}
